### ISSUE TITLE
Travis always fails for users outside of Github org

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/sinnerschrader-website#29]
The Travis build always fails for users without writing access contributing PRs. 

Example build: [Travis CI](https://travis-ci.org/sinnerschrader/sinnerschrader-website/builds/177122194)
Failing line: [Travis CI L350](https://travis-ci.org/sinnerschrader/sinnerschrader-website/builds/177122194#L350)

The problem appears to emanate from [deploy.sh#L42](https://github.com/sinnerschrader/sinnerschrader-website/blob/f9dc07a0aa8245730fe7c3c3d4f7b7b82439a2bd/deploy.sh#L42). According to [docs.travis-ci.com](https://docs.travis-ci.com/user/environment-variables/#Convenience-Variables) we can check for `TRAVIS_SECURE_ENV_VARS` and `TRAVIS_PULL_REQUEST` to determine if we want to try and deploy at all.

### Blocked
* https://github.com/sinnerschrader/sinnerschrader-website/pull/27

**Comment by KnisterPeter** [comment]
Currently this is correct. The workflow need to be defined but I think for now it is okay, since 'external' contributes need to be tested twice. And any developer with write access should be able to push and merge the required changes. (This need to be tested tho).
If you have a better process in mind for building and pushing from travis then layout the ideas here.
[deploy.sh#L42](https://github.com/sinnerschrader/sinnerschrader-website/blob/f9dc07a0aa8245730fe7c3c3d4f7b7b82439a2bd/deploy.sh#L42) explicitly catches the error and sets a correct error message. If you remove that, than the deploy key could just not be decoded and the error message is 'iv undefined' - from an invalid `openssl` invocation.

**Comment by marionebl** [comment]
My proposed solution is outlined in https://github.com/sinnerschrader/sinnerschrader-website/pull/31/commits/24ffe8e04303c9f4f66063207039102424fc6500

Boils down to
* "build" and "deploy" are different and distinct phases on CI
* Every CI performs a "build", which serves as test in our case
* Only authorized runs - PRs landed on master, that is, perform a "deploy"
* Everybody else exits early with a zero exit code

**Comment by KnisterPeter** [comment]
This is not possible since `master` is a protected branch. Travis - even with deploy key - is not able to push something to master. Therefore a push is required since only 'write' enabled users could create a push and have the encryption data in travis available and are enabled to push. It's not as easy as it may look. I'm a bit sad about it.

**Comment by marionebl** [comment]
We could allow Travis to push onto master via Github's **Restrict who can push to this branch** option:

<img width="767" alt="bildschirmfoto 2016-11-19 um 00 43 33" src="https://cloud.githubusercontent.com/assets/4248851/20450491/5bb90edc-adf1-11e6-88e8-e30992111213.png">

**Comment by KnisterPeter** [comment]
I failed to do so. Maybe I've overlooked something?

**Comment by neumannrf** [comment]
@marionebl @KnisterPeter I was trying to do the same in my repository. Every PR accepted into `master` triggers a version update of the `package.json` which **must be pushed to `master`**. 

I couldn't find a way around it (other than un-protecting the `master` branch). Did you eventually found a solution?

**Comment by KnisterPeter** [comment]
As far as I know it is not possible
